// archive/v4/frontend-creat-react-tailwind/src/components/Button.tsx
import React from 'react';

interface IButton {
  value: string;
  upperCase?: boolean;
  onClick?: () => void;
  styleName?: 'important' | 'normal' | 'bold';
  className?: string;
  disabled?: boolean;
}

export default function Button(props: IButton) {
  const upper = props.upperCase ? props.upperCase : true;
  const value = upper ? props.value.toUpperCase() : props.value;
  const optionalStyle =
    props.styleName === 'important'
      ? 'bg-blue-400 hover:bg-blue-500 text-white px-4 py-2 rounded-lg shadow'
      : props.styleName === 'bold'
      ? 'border bg-gray-200 hover:bg-gray-50 px-2 rounded shadow-sm'
      : 'border bg-gray-50 hover:bg-gray-100 px-2 rounded shadow-sm';
  const style = 'cursor-pointer w-min transition duration-200 ' + optionalStyle + ' ' + props.className;

  return <input type="button" value={value} onClick={props.onClick} className={style} disabled={props.disabled} />;
}

// frontend/src/components/Button.svelte
<script lang="ts">
  export let value: string;
  export let onClick: (e) => void;
  export let type: "button" | "submit" = "button";
  export let spec: "important" | "normal" | "bold" = "normal";
  export let className: string = "";
  export let disabled: boolean = false;

  const buildStyle = () => {
    let style = "cursor-pointer w-min transition duration-200";
    if (className) {
      style += " " + className;
    }

    switch (spec) {
      case "important":
        style +=
          " bg-blue-400 hover:bg-blue-500 text-white px-4 py-2 rounded-lg shadow";
        break;
      case "bold":
        style += " border bg-gray-200 hover:bg-gray-50 px-2 rounded shadow-sm";
      default:
        style += " border bg-gray-50 hover:bg-gray-100 px-2 rounded shadow-sm";
        break;
    }

    return style;
  };
</script>

<input {type} {value} {disabled} class={buildStyle()} on:click={onClick} />
